apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "cos-webhook.weimob.devops"
webhooks:
  - name: "cos-webhook.weimob.devops"
    namespaceSelector:
      matchLabels:
        admission-webhook: enabled
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE","UPDATE","DELETE"]
        resources: ["pods"]
        scope: "Namespaced"
    clientConfig:
#       service:
#         namespace: cos-opa
#         name: cos-webhook
#         path: /validate
#         port: 443
      url: https://192.168.118.1:443/validate
      admissionReviewVersions: ["v1"]
      sideEffects: None
      caBundle: |
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURIekNDQWdlZ0F3SUJBZ0lVY203U1hTa2Y5
        eDBZNEpwK2duS1c4eUxCTm9vd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0h6RUxNQWtHQTFVRUJoTUNR
        VlV4RURBT0JnTlZCQU1NQjJOdmN5MXZjR0V3SGhjTk1qSXdNakEzTURrMApNalExV2hjTk1qTXdN
        akEzTURrME1qUTFXakFmTVFzd0NRWURWUVFHRXdKQlZURVFNQTRHQTFVRUF3d0hZMjl6CkxXOXdZ
        VENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFMV0o5d1hZUWdHY3VN
        V2QKY056UW5QZTJlZWE1WlJ2bzQzdEkwcXVLOHdORzh0WHkvWmhZZkZqZld3STRzMzFucGlSM0J0
        SkwrUTdQVTJUVAo0cWhYNFpKa3lKeHp6RHY1eUZZcmxLc3ZJdnp1NEtHWkY2aU1ZSWNEM1BKRWtp
        NnhMMGhWbGhVVldVczFPbHkrCnR6SWV1T1JhOW5Td2Y1VUdHUHNBTDNJVkxIVEJJYWlyUjFvbzN4
        V0ZSK2xsbzl2bmpZcUFxaGFMV1RWUWhZcDYKMzViOHBPbzZocTMycnVyczNvZG5jTmdPQlMvcFdq
        eUt1RjY0L2NtT2c0Ui9pSXlycUxMREp5b0pTZXVDK21UQQpZV3ZiRkFuNnBGUTdIZktmQm53SkUy
        aTVEZUxzSjROaWtHWmEwbGVlWm82b0dLZHBQcEhhbVN5dG1xSkVtcDVoClJ1bklqVWtDQXdFQUFh
        TlRNRkV3SFFZRFZSME9CQllFRktFZGJxQWdsd0xDNFRqNjR6K3NnUWpKY1UwaE1COEcKQTFVZEl3
        UVlNQmFBRktFZGJxQWdsd0xDNFRqNjR6K3NnUWpKY1UwaE1BOEdBMVVkRXdFQi93UUZNQU1CQWY4
        dwpEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBREZXd1BpaTB1djB1UHRWY2VIQWtqeDI3N3BRcmFF
        Y21mNXlXUXJMCnNBMnorbjN5bEJFL3ViZWlxaHhIUmJZd0xHeE1MSEdLOG5PZGNTdE9NR3NDMjJW
        SjE0RC9DcGt6UmNjVlhqd2gKTlJMVnl0VXQyZ3V3c0VaZ2xWc29PUW1saG5UalhqWkh1RHZPT01a
        eUlxMDNaekNTeGJiclUvTzNPdTE5dXJ3MQp1Q0RsRGdiQVN1NWZIczhoTnJXaUZjMVh4c3MrWjFN
        a3p5WmliVzlISmd2U0tOWkdKL3VMSGk0a2sraGRUSXl5CmlQZHNKV25WODZWcTFtYkpFN0N3M2k4
        Q1FFd3Y4VHBTQTlib1hkNXFRb3Y2YjVaMVJDYzQ0M0xibUY3MGNwSkIKMWQ5aGxzSzlib1ZFaWhR
        cmtPNVFBYkQyRWVhb1BjMjVQd2lnRlJTeU9yTlRCNmc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0t
        LS0K